import TitleBar from "@components/TitleBar";
import "@css/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useRef } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full flex flex-col`}>
        <TitleBar />
        <main className="w-full mt-12">{children}</main>
      </body>
    </html>
  );
}
