const lastTimestamp = new Date().getTime();
export const accounts: TAccount[] = [
  {
    id: "1",
    email: "yektamain@gmail.com",
    title: "Yekta Main",
    iconColor: "green",
    iconType: "trophy",
  },
  {
    id: "2",
    email: "yektasecondary@gmail.com",
    title: "Yekta Secondary",
    iconColor: "yellow",
    iconType: "rocket",
  },
  {
    id: "3",
    email: "hello@work.com",
    title: "Work",
    iconColor: "purple",
    iconType: "work",
  },
  {
    id: "4",
    email: "yekta@school.com",
    title: "School",
    iconColor: "red",
    iconType: "school",
  },
];

export const emails: TEmail[] = [
  {
    sender: "GitHub",
    title:
      "[GitHub] A third-party OAuth application has been added to your account",
    body: "Hey​ ​yekta! A​ ​third-party​ ​OAuth​ ​application​ ​(Test App)​ ​with​ ​read:user​ ​and​ ​user:email​ ​scopes​ ​was​ ​recently​ ​authorized​ ​to​ ​access​ ​your​ ​account.",
    date: "2023-09-13T06:00:00.000Z",
    account: accounts[0],
    isRead: false,
    isFavorited: false,
  },
  {
    sender: "Workplace",
    title: "Your meeting with the marketing team is scheduled for tomorrow.",
    body: "Hi there! Just a quick reminder about your meeting tomorrow at 3pm with the marketing team.",
    date: "2023-09-13T05:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "DevOps",
    title: "Build #2345 failed!",
    body: "Hello, unfortunately, the recent build #2345 has failed. Please check the logs for more details.",
    date: "2023-09-13T04:00:00.000Z",
    account: accounts[0],
    isRead: false,
    isFavorited: true,
  },
  {
    sender: "Real Estate",
    title: "New property listing in your area!",
    body: "Good news! A new property that matches your preferences has been listed in your area. Check it out now!",
    date: "2023-09-13T03:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "University",
    title: "Enrollment confirmation for next semester",
    body: "We're pleased to inform you that you've been enrolled for the next semester. Check your course list online.",
    date: "2023-09-12T06:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Updated benefits package",
    body: "We've made some updates to the benefits package. Please review the new documentation attached.",
    date: "2023-09-12T05:00:00.000Z",
    account: accounts[1],
    isRead: false,
    isFavorited: true,
  },
  {
    sender: "Tech Team",
    title: "Server maintenance downtime",
    body: "Scheduled server maintenance will occur tonight from 2-3am. Expect some downtime.",
    date: "2023-09-12T04:00:00.000Z",
    account: accounts[3],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Property Manager",
    title: "Scheduled power outage",
    body: "A scheduled power outage will take place tomorrow from 9am-11am for routine maintenance.",
    date: "2023-09-12T03:00:00.000Z",
    account: accounts[2],
    isRead: false,
    isFavorited: true,
  },
  {
    sender: "University",
    title: "Enrollment confirmation for next semester",
    body: "We're pleased to inform you that you've been enrolled for the next semester. Check your course list online.",
    date: "2023-09-11T05:00:00.000Z",
    account: accounts[3],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR Department",
    title: "Updated benefits package",
    body: "We've made some updates to the benefits package. Please review the new documentation attached.",
    date: "2023-09-11T04:00:00.000Z",
    account: accounts[2],
    isRead: false,
    isFavorited: true,
  },
  {
    sender: "Tech Team",
    title: "Server maintenance downtime",
    body: "Scheduled server maintenance will occur tonight from 2-3am. Expect some downtime.",
    date: "2023-09-11T03:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Property Manager",
    title: "Scheduled power outage",
    body: "A scheduled power outage will take place tomorrow from 9am-11am for routine maintenance.",
    date: "2023-09-10T11:00:00.000Z",
    account: accounts[2],
    isRead: false,
    isFavorited: false,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-09-10T11:00:00.000Z",
    account: accounts[3],
    isRead: false,
    isFavorited: false,
  },
  {
    sender: "Team Leads",
    title: "Weekly sync-up rescheduled",
    body: "Our weekly sync-up has been moved to Thursday. Please update your calendars.",
    date: "2023-09-10T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Web Admin",
    title: "Website update successful",
    body: "The latest updates to our website have been successfully deployed without issues.",
    date: "2023-09-10T11:00:00.000Z",
    account: accounts[1],
    isRead: false,
    isFavorited: false,
  },
  {
    sender: "City Council",
    title: "New zoning laws",
    body: "New zoning laws have been passed in your area. Check the attached document for details.",
    date: "2023-09-10T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Online Course",
    title: "Certification exam next week",
    body: "A reminder that your certification exam is scheduled for next week.",
    date: "2023-09-10T11:00:00.000Z",
    account: accounts[3],
    isRead: false,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "SysAdmin",
    title: "New software updates",
    body: "Please ensure your systems are updated with the latest software patches.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Real Estate Agency",
    title: "Viewing appointment confirmation",
    body: "Your viewing appointment for the apartment on Elm Street has been confirmed for Saturday.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Alumni Association",
    title: "Annual alumni meet",
    body: "You're invited to the annual alumni meet next month. RSVP by next week.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[3],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Company Retreat",
    title: "Details for the upcoming company retreat",
    body: "Find attached the itinerary and details for the upcoming company retreat.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Hosting Provider",
    title: "Scheduled server upgrades",
    body: "We will be performing server upgrades on Sunday from 1am-4am.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Construction Update",
    title: "Updated timeline for roadwork",
    body: "The roadwork on Maple Ave will now be completed by the end of next month.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR Department",
    title: "Updated benefits package",
    body: "We've made some updates to the benefits package. Please review the new documentation attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: false,
    isFavorited: false,
  },
  {
    sender: "Tech Team",
    title: "Server maintenance downtime",
    body: "Scheduled server maintenance will occur tonight from 2-3am. Expect some downtime.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Property Manager",
    title: "Scheduled power outage",
    body: "A scheduled power outage will take place tomorrow from 9am-11am for routine maintenance.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: false,
    isFavorited: false,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[3],
    isRead: false,
    isFavorited: false,
  },
  {
    sender: "Team Leads",
    title: "Weekly sync-up rescheduled",
    body: "Our weekly sync-up has been moved to Thursday. Please update your calendars.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Web Admin",
    title: "Website update successful",
    body: "The latest updates to our website have been successfully deployed without issues.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "City Council",
    title: "New zoning laws",
    body: "New zoning laws have been passed in your area. Check the attached document for details.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Online Course",
    title: "Certification exam next week",
    body: "A reminder that your certification exam is scheduled for next week.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[3],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "SysAdmin",
    title: "New software updates",
    body: "Please ensure your systems are updated with the latest software patches.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Real Estate Agency",
    title: "Viewing appointment confirmation",
    body: "Your viewing appointment for the apartment on Elm Street has been confirmed for Saturday.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Alumni Association",
    title: "Annual alumni meet",
    body: "You're invited to the annual alumni meet next month. RSVP by next week.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[3],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Company Retreat",
    title: "Details for the upcoming company retreat",
    body: "Find attached the itinerary and details for the upcoming company retreat.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Hosting Provider",
    title: "Scheduled server upgrades",
    body: "We will be performing server upgrades on Sunday from 1am-4am.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Construction Update",
    title: "Updated timeline for roadwork",
    body: "The roadwork on Maple Ave will now be completed by the end of next month.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Construction Update",
    title: "Updated timeline for roadwork",
    body: "The roadwork on Maple Ave will now be completed by the end of next month.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Construction Update",
    title: "Updated timeline for roadwork",
    body: "The roadwork on Maple Ave will now be completed by the end of next month.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Construction Update",
    title: "Updated timeline for roadwork",
    body: "The roadwork on Maple Ave will now be completed by the end of next month.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Construction Update",
    title: "Updated timeline for roadwork",
    body: "The roadwork on Maple Ave will now be completed by the end of next month.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Construction Update",
    title: "Updated timeline for roadwork",
    body: "The roadwork on Maple Ave will now be completed by the end of next month.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Construction Update",
    title: "Updated timeline for roadwork",
    body: "The roadwork on Maple Ave will now be completed by the end of next month.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Construction Update",
    title: "Updated timeline for roadwork",
    body: "The roadwork on Maple Ave will now be completed by the end of next month.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Construction Update",
    title: "Updated timeline for roadwork",
    body: "The roadwork on Maple Ave will now be completed by the end of next month.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Construction Update",
    title: "Updated timeline for roadwork",
    body: "The roadwork on Maple Ave will now be completed by the end of next month.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: false,
    isFavorited: false,
  },
  {
    sender: "Construction Update",
    title: "Updated timeline for roadwork",
    body: "The roadwork on Maple Ave will now be completed by the end of next month.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Construction Update",
    title: "Updated timeline for roadwork",
    body: "The roadwork on Maple Ave will now be completed by the end of next month.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "SysAdmin",
    title: "New software updates",
    body: "Please ensure your systems are updated with the latest software patches.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "SysAdmin",
    title: "New software updates",
    body: "Please ensure your systems are updated with the latest software patches.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "SysAdmin",
    title: "New software updates",
    body: "Please ensure your systems are updated with the latest software patches.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "SysAdmin",
    title: "New software updates",
    body: "Please ensure your systems are updated with the latest software patches.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "SysAdmin",
    title: "New software updates",
    body: "Please ensure your systems are updated with the latest software patches.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "SysAdmin",
    title: "New software updates",
    body: "Please ensure your systems are updated with the latest software patches.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "SysAdmin",
    title: "New software updates",
    body: "Please ensure your systems are updated with the latest software patches.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "SysAdmin",
    title: "New software updates",
    body: "Please ensure your systems are updated with the latest software patches.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "SysAdmin",
    title: "New software updates",
    body: "Please ensure your systems are updated with the latest software patches.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "SysAdmin",
    title: "New software updates",
    body: "Please ensure your systems are updated with the latest software patches.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-09-08T11:00:00.000Z",
    account: accounts[3],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-09-08T11:00:00.000Z",
    account: accounts[3],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-09-08T11:00:00.000Z",
    account: accounts[3],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-09-08T11:00:00.000Z",
    account: accounts[3],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-09-08T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-09-08T11:00:00.000Z",
    account: accounts[1],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[3],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[3],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[0],
    isRead: true,
    isFavorited: true,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "2023-08-10T11:00:00.000Z",
    account: accounts[1],
    isRead: false,
    isFavorited: true,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "2023-09-09T11:00:00.000Z",
    account: accounts[2],
    isRead: true,
    isFavorited: false,
  },
]
  .map((e) => ({ ...e, date: new Date(lastTimestamp) }))
  .map((e, i) => ({
    ...e,
    id: `${i}`,
    date: new Date(
      lastTimestamp -
        i *
          1000 *
          60 *
          60 *
          (i > 90 ? 96 : i > 75 ? 48 : i > 70 ? 24 : i > 40 ? 12 : 2)
    ).toUTCString(),
  }));

export const unreadEmails = emails.filter((email) => !email.isRead);
export const favoritedEmails = emails.filter((email) => email.isFavorited);

export type TIconColor =
  | "red"
  | "lime"
  | "blue"
  | "yellow"
  | "green"
  | "purple"
  | "on-bg"
  | "placeholder";

export type TAccountAvatarIcon =
  | "school"
  | "work"
  | "terminal"
  | "building"
  | "trophy"
  | "rocket"
  | "command-line";

export type TIconType =
  | TAccountAvatarIcon
  | "inbox"
  | "placeholder"
  | "unread"
  | "favorites";

export interface TAccount {
  id: string;
  email: string;
  title: string;
  iconColor: TIconColor;
  iconType: TAccountAvatarIcon;
}

export interface TEmail {
  id: string;
  sender: string;
  title: string;
  body: string;
  isRead: boolean;
  isFavorited: boolean;
  date: string;
  account: TAccount;
}
