import type { TEmailLineProps } from "@components/EmailLine/EmailLine";

export const emails: TEmailLineProps[] = [
  {
    sender: "GitHub",
    title:
      "[GitHub] A third-party OAuth application has been added to your account",
    body: "Hey​ ​yekta! A​ ​third-party​ ​OAuth​ ​application​ ​(Test App)​ ​with​ ​read:user​ ​and​ ​user:email​ ​scopes​ ​was​ ​recently​ ​authorized​ ​to​ ​access​ ​your​ ​account.",
    date: "2h",
    iconColor: "red",
    iconType: "school",
    isRead: false,
  },
  {
    sender: "Workplace",
    title: "Your meeting with the marketing team is scheduled for tomorrow.",
    body: "Hi there! Just a quick reminder about your meeting tomorrow at 3pm with the marketing team.",
    date: "5h",
    iconColor: "lime",
    iconType: "work",
    isRead: true,
  },
  {
    sender: "DevOps",
    title: "Build #2345 failed!",
    body: "Hello, unfortunately, the recent build #2345 has failed. Please check the logs for more details.",
    date: "10h",
    iconColor: "lightblue",
    iconType: "terminal",
    isRead: false,
  },
  {
    sender: "Real Estate",
    title: "New property listing in your area!",
    body: "Good news! A new property that matches your preferences has been listed in your area. Check it out now!",
    date: "11h",
    iconColor: "yellow",
    iconType: "building",
    isRead: true,
  },
  {
    sender: "University",
    title: "Enrollment confirmation for next semester",
    body: "We're pleased to inform you that you've been enrolled for the next semester. Check your course list online.",
    date: "13h",
    iconColor: "red",
    iconType: "school",
    isRead: true,
  },
  {
    sender: "HR",
    title: "Updated benefits package",
    body: "We've made some updates to the benefits package. Please review the new documentation attached.",
    date: "15h",
    iconColor: "lime",
    iconType: "work",
    isRead: false,
  },
  {
    sender: "Tech Team",
    title: "Server maintenance downtime",
    body: "Scheduled server maintenance will occur tonight from 2-3am. Expect some downtime.",
    date: "19h",
    iconColor: "lightblue",
    iconType: "terminal",
    isRead: true,
  },
  {
    sender: "Property Manager",
    title: "Scheduled power outage",
    body: "A scheduled power outage will take place tomorrow from 9am-11am for routine maintenance.",
    date: "24 Aug",
    iconColor: "yellow",
    iconType: "building",
    isRead: false,
  },
  {
    sender: "University",
    title: "Enrollment confirmation for next semester",
    body: "We're pleased to inform you that you've been enrolled for the next semester. Check your course list online.",
    date: "24 Aug",
    iconColor: "red",
    iconType: "school",
    isRead: true,
  },
  {
    sender: "HR Department",
    title: "Updated benefits package",
    body: "We've made some updates to the benefits package. Please review the new documentation attached.",
    date: "24 Aug",
    iconColor: "lime",
    iconType: "work",
    isRead: false,
  },
  {
    sender: "Tech Team",
    title: "Server maintenance downtime",
    body: "Scheduled server maintenance will occur tonight from 2-3am. Expect some downtime.",
    date: "24 Aug",
    iconColor: "lightblue",
    iconType: "terminal",
    isRead: true,
  },
  {
    sender: "Property Manager",
    title: "Scheduled power outage",
    body: "A scheduled power outage will take place tomorrow from 9am-11am for routine maintenance.",
    date: "24 Aug",
    iconColor: "yellow",
    iconType: "building",
    isRead: false,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "24 Aug",
    iconColor: "red",
    iconType: "school",
    isRead: false,
  },
  {
    sender: "Team Leads",
    title: "Weekly sync-up rescheduled",
    body: "Our weekly sync-up has been moved to Thursday. Please update your calendars.",
    date: "24 Aug",
    iconColor: "lime",
    iconType: "work",
    isRead: true,
  },
  {
    sender: "Web Admin",
    title: "Website update successful",
    body: "The latest updates to our website have been successfully deployed without issues.",
    date: "24 Aug",
    iconColor: "lightblue",
    iconType: "terminal",
    isRead: false,
  },
  {
    sender: "City Council",
    title: "New zoning laws",
    body: "New zoning laws have been passed in your area. Check the attached document for details.",
    date: "24 Aug",
    iconColor: "yellow",
    iconType: "building",
    isRead: true,
  },
  {
    sender: "Online Course",
    title: "Certification exam next week",
    body: "A reminder that your certification exam is scheduled for next week.",
    date: "24 Aug",
    iconColor: "red",
    iconType: "school",
    isRead: false,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "24 Aug",
    iconColor: "lime",
    iconType: "work",
    isRead: true,
  },
  {
    sender: "SysAdmin",
    title: "New software updates",
    body: "Please ensure your systems are updated with the latest software patches.",
    date: "24 Aug",
    iconColor: "lightblue",
    iconType: "terminal",
    isRead: true,
  },
  {
    sender: "Real Estate Agency",
    title: "Viewing appointment confirmation",
    body: "Your viewing appointment for the apartment on Elm Street has been confirmed for Saturday.",
    date: "24 Aug",
    iconColor: "yellow",
    iconType: "building",
    isRead: true,
  },
  {
    sender: "Alumni Association",
    title: "Annual alumni meet",
    body: "You're invited to the annual alumni meet next month. RSVP by next week.",
    date: "24 Aug",
    iconColor: "red",
    iconType: "school",
    isRead: true,
  },
  {
    sender: "Company Retreat",
    title: "Details for the upcoming company retreat",
    body: "Find attached the itinerary and details for the upcoming company retreat.",
    date: "24 Aug",
    iconColor: "lime",
    iconType: "work",
    isRead: true,
  },
  {
    sender: "Hosting Provider",
    title: "Scheduled server upgrades",
    body: "We will be performing server upgrades on Sunday from 1am-4am.",
    date: "24 Aug",
    iconColor: "lightblue",
    iconType: "terminal",
    isRead: true,
  },
  {
    sender: "Construction Update",
    title: "Updated timeline for roadwork",
    body: "The roadwork on Maple Ave will now be completed by the end of next month.",
    date: "24 Aug",
    iconColor: "yellow",
    iconType: "building",
    isRead: true,
  },
  {
    sender: "HR Department",
    title: "Updated benefits package",
    body: "We've made some updates to the benefits package. Please review the new documentation attached.",
    date: "24 Aug",
    iconColor: "lime",
    iconType: "work",
    isRead: false,
  },
  {
    sender: "Tech Team",
    title: "Server maintenance downtime",
    body: "Scheduled server maintenance will occur tonight from 2-3am. Expect some downtime.",
    date: "24 Aug",
    iconColor: "lightblue",
    iconType: "terminal",
    isRead: true,
  },
  {
    sender: "Property Manager",
    title: "Scheduled power outage",
    body: "A scheduled power outage will take place tomorrow from 9am-11am for routine maintenance.",
    date: "24 Aug",
    iconColor: "yellow",
    iconType: "building",
    isRead: false,
  },
  {
    sender: "Educational Forum",
    title: "Upcoming seminar on modern teaching methods",
    body: "Join our seminar next week to learn about the most effective teaching methods.",
    date: "24 Aug",
    iconColor: "red",
    iconType: "school",
    isRead: false,
  },
  {
    sender: "Team Leads",
    title: "Weekly sync-up rescheduled",
    body: "Our weekly sync-up has been moved to Thursday. Please update your calendars.",
    date: "23 Aug",
    iconColor: "lime",
    iconType: "work",
    isRead: true,
  },
  {
    sender: "Web Admin",
    title: "Website update successful",
    body: "The latest updates to our website have been successfully deployed without issues.",
    date: "23 Aug",
    iconColor: "lightblue",
    iconType: "terminal",
    isRead: true,
  },
  {
    sender: "City Council",
    title: "New zoning laws",
    body: "New zoning laws have been passed in your area. Check the attached document for details.",
    date: "23 Aug",
    iconColor: "yellow",
    iconType: "building",
    isRead: true,
  },
  {
    sender: "Online Course",
    title: "Certification exam next week",
    body: "A reminder that your certification exam is scheduled for next week.",
    date: "23 Aug",
    iconColor: "red",
    iconType: "school",
    isRead: true,
  },
  {
    sender: "HR",
    title: "Office health guidelines",
    body: "Please review the updated office health and safety guidelines attached.",
    date: "23 Aug",
    iconColor: "lime",
    iconType: "work",
    isRead: true,
  },
  {
    sender: "SysAdmin",
    title: "New software updates",
    body: "Please ensure your systems are updated with the latest software patches.",
    date: "23 Aug",
    iconColor: "lightblue",
    iconType: "terminal",
    isRead: true,
  },
  {
    sender: "Real Estate Agency",
    title: "Viewing appointment confirmation",
    body: "Your viewing appointment for the apartment on Elm Street has been confirmed for Saturday.",
    date: "23 Aug",
    iconColor: "yellow",
    iconType: "building",
    isRead: true,
  },
  {
    sender: "Alumni Association",
    title: "Annual alumni meet",
    body: "You're invited to the annual alumni meet next month. RSVP by next week.",
    date: "23 Aug",
    iconColor: "red",
    iconType: "school",
    isRead: true,
  },
  {
    sender: "Company Retreat",
    title: "Details for the upcoming company retreat",
    body: "Find attached the itinerary and details for the upcoming company retreat.",
    date: "23 Aug",
    iconColor: "lime",
    iconType: "work",
    isRead: true,
  },
  {
    sender: "Hosting Provider",
    title: "Scheduled server upgrades",
    body: "We will be performing server upgrades on Sunday from 1am-4am.",
    date: "23 Aug",
    iconColor: "lightblue",
    iconType: "terminal",
    isRead: true,
  },
  {
    sender: "Construction Update",
    title: "Updated timeline for roadwork",
    body: "The roadwork on Maple Ave will now be completed by the end of next month.",
    date: "23 Aug",
    iconColor: "yellow",
    iconType: "building",
    isRead: true,
  },
];
